FROM archlinux:latest

# パッケージのインストール
RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm --needed \
    pacman -S --noconfirm --needed \
    base-devel \
    git \
    wget \
    texinfo \
    gnupg \
    evince \
    bison \
    jdk-openjdk \
    java-runtime-common \
    texlive-bin
    libxaw \
    ncurses \
    freeglut

# install AUR
WORKDIR /tmp
RUN git clone https://aur.archl
inux.org/yai.git
WORKDIR /tmp/yay
RUN makepkg -si

# update yay
RUN yay -Syu
#
RUN yay -S nkf latex2html texi2html sharutils
RUN pacman -S emacs clang
ENV CC=clang

# OpenXM の取得
RUN git clone https://github.com/openxm-org/OpenXM /OpenXM && \
    git clone https://github.com/openxm-org/OpenXM_contrib2 /OpenXM_contrib2

WORKDIR /OpenXM/src
ENV PATH="/OpenXM/bin:${PATH}"

WORKDIR /OpenXM/src
RUN make configure
RUN make install
WORKDIR /OpenXM/rc
RUN make
RUN cp openxm /usr/local/bin
RUN openxm user-asir-mode.sh --local-yes

