FROM --platform=linux/i386 debian:wheezy-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8

USER root

RUN printf "deb http://archive.debian.org/debian wheezy main\n" > /etc/apt/sources.list && \
    printf "deb http://archive.debian.org/debian-security wheezy/updates main\n" >> /etc/apt/sources.list && \
    printf 'Acquire::Check-Valid-Until "false";\nAcquire::AllowInsecureRepositories "true";\nAcquire::AllowDowngradeToInsecureRepositories "true";\n' > /etc/apt/apt.conf.d/99no-check-valid && \
    apt-get -o Acquire::AllowInsecureRepositories=true update

# Development environment
RUN apt-get update && apt-get -y --allow-unauthenticated install --no-install-recommends \
    build-essential \
    ca-certificates \
    libgc-dev \
    bison \
    flex \
    libncurses5-dev \
    tcl-dev \
    tk-dev \
    texinfo \
    wget \
    vim-tiny 

# Get Sather
WORKDIR /opt
RUN wget https://ftp.gnu.org/gnu/sather/sather-1.2.3.tar.gz
RUN tar xvzf sather-1.2.3.tar.gz
RUN ln -s sather-1.2.3 sather
RUN rm sather-1.2.3.tar.gz

# Collision of sather and glibc
#RUN sed -i 's/^#define isnormal(/#ifndef isnormal\n#define isnormal(/' \
#  /opt/sather/System/Common/runtime.h

# Make Sather
WORKDIR /opt/sather
RUN make

# Environment variables
ENV SATHER_HOME="/opt/sather"
ENV PATH="/opt/sather/Bin:${PATH}"

# General user
RUN useradd -m -s /bin/bash user
USER user
WORKDIR /home/user
RUN mkdir -p /home/user/work

CMD ["bash"]
